name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for GitHub to generate an OIDC token
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Secrets from Infisical
        uses: Infisical/secrets-action@v1.0.9
        with:
          method: oidc  # Use OIDC authentication
          identity-id: ${{ secrets.MACHINE_IDENTITY_CLIENT_ID }}  # Set the identity ID
          oidc-audience: "https://github.com/0xArshdeep"
          project-slug: "integrations-6-vsv"  # Replace with your Infisical project slug
          env-slug: "dev"  # Replace with the Infisical environment slug
